eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer3:8888/eureka
    prefer-same-zone-eureka: true
server:
  port: 9985
spring:
  application:
    name: zuul-gate-way
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    password: topmdrt!@#$
    host: 172.18.57.145

zuul:
#  ignored-patterns: /**
  routes:
    demo-web:
      path: /demo/**
      strip-prefix: true
      service-id: DEMO-WEB
  set-content-length: true
  sensitive-headers: X-GLOBAL-SESSION
  #只开放配置的地址
