eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer3:8888/eureka
    prefer-same-zone-eureka: true
server:
  port: 9985
spring:
  application:
    name: zuul-gate-way
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
#    password: topmdrt!@#$
#    host: 172.18.57.145
    host: localhost
    port: 6379
  profiles:
    include:
      - auth

zuul:
  routes:
    demo-web:
      path: /demo2/**
      strip-prefix: true
      service-id: DEMO-WEB-2
  set-content-length: true
#  sensitive-headers: X-GLOBAL-SESSION
  #只开放配置的地址
