eureka:
  instance:
    appname: gate-way
  client:
    #可以放服务注入特定的空间中
    service-url:
      #默认空间defaultZone:
      #      defaultZone: http://eureka-peer1:9980/eureka/,http://peer3:8888/eureka/
      defaultZone: http://peer1:8888/eureka/
    #优先使用同zone的服务，默认为true(eureka.instance.metadata-map )
    prefer-same-zone-eureka: true
spring:
  application:
    name: gate-way
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  cloud:
    gateway:
      routes:
        - id: demo-web
          uri: lb://demo-web
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: server-one
          uri: lb://WX-GATE-V1
          predicates:
            - Path=/wx/**
          filters:
            - StripPrefix=1
  redis:
    host: 10.66.94.117
    port: 6379
    password: topmdrt!@#$
server:
  port: 9985
zuul:
  routes:
    demo-web:
      path: /demo/**
      strip-prefix: true
      service-id: DEMO-WEB
    wx-gate-api:
      path: /wx/**
      strip-prefix: true
      service-id: wx-gate-v1
  set-content-length: true
  sensitive-headers:
