profiles:
  name: peer2
eureka:
  client:
    service-url:
        defaultZone: http://eureka-peer1:9980/eureka,http://eureka-peer2:9979/eureka
    register-with-eureka: false
  instance:
    hostname: eureka-${profiles.name}
server:
  port: 9979
