spring:
  application:
    name: ribbon-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer1:9980/eureka
    #设置获取服务清单的时间,默认30秒
    registry-fetch-interval-seconds: 30
  instance:
    appname: ribbon-service
server:
  port: 9983
