eureka:
  instance:
    appname: demo-web
spring:
  application:
    name: demo-web
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    host: 10.66.94.117
    port: 6379
    password: topmdrt!@#$