eureka:
  instance:
    prefer-ip-address: true
spring:
  application:
    name: demo-web-2
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
#    host: 172.18.57.145
#    password: topmdrt!@#$
    host: localhost
    port: 6379
  profiles:
    active: peer1
