eureka:
  client:
    service-url:
      defaultZone: http://localhost:9980/eureka
  instance:
      prefer-ip-address: true
server:
  port: 7000
spring:
  application:
    name: auth-center
  redis:
#    password: topmdrt!@#$
#    host: 172.18.57.145
    host: localhost
    port: 6379
