spring:
  application:
    name: auth-center
  redis:
    password: topmdrt!@#$
    host: 172.18.57.145
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8888/eureka
server:
  port: 7000
