profiles:
  name: peer2
eureka:
  client:
    service-url:
      ctchan-zone: http://localhost:9980/eureka
  instance:
    hostname: eureka-${profiles.name}
    metadata-map:
      zone: defaultZone
server:
  port: 9979
